### ISSUE TITLE
Constant lag

### ISSUE THREAD

**Issue by RagaRBM** [AEnterprise/Buildcraft-Additions#155]
BCA 2.0 beta build, BC 6.3.0.
When I'm on my world with BCA 2.0, I noticed the frame rate stutters constantly. But the frame rate is fine if I use BCA 1.8.4.
I noticed the game log also constantly generating these messages (and each time the message appears, the game lagged) :

[14:12:01] [Server thread/ERROR] [FML]: A TileEntity type buildcraftAdditions.tileEntities.TileBasicCoil has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.RuntimeException: class buildcraftAdditions.tileEntities.TileBasicCoil is missing a mapping! This is a bug!
	at net.minecraft.tileentity.TileEntity.func_145841_b(TileEntity.java:80) ~[aor.class:?]
	at buildcraftAdditions.tileEntities.Bases.TileCoilBase.func_145841_b(TileCoilBase.java:46) ~[TileCoilBase.class:?]
	at buildcraftAdditions.tileEntities.TileBasicCoil.func_145841_b(TileBasicCoil.java:56) ~[TileBasicCoil.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:370) [aqk.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:197) [aqk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:256) [ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:302) [ms.class:?]
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:808) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by AEnterprise** [comment]
thanks alot, these are the kinds of bugs i wana have found and fixed

how often do these messages apear? i'll look more in depth in my test world this weekend (currently at school)

**Comment by AEnterprise** [comment]
@RagaRBM quick code checking and i found the bug and it is realy a MASSIVE screwup, edited online but should work, will send you a new build when i get home, you will probably have lost everything that was in any BCA machine at the time you exited your world so don't re-enter it until you have a new build otherwise you'll lose stuff again when exiting it the next time

i aplologize for the massive scewup and any stuff you might have lost due to this bug but i'm glad you found it.

i hope this fixes the lag, if it doesn't it's probably my networking code that's responsible still have some finishing up of the unification to do and some things are sending updates way to often atm
